language: node_js
node_js:
- lts/*
- node
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: hadrien.milano@gmail.com
  api_key:
    secure: WN1gUk0fo5mesODLJpsZgav6IpVnMf0DpBFdwKkNu/jolglB1ckjF5vVxhgCnPgyAsY/PyHaTqTk7QMbVB32vOwAaIShrucEgwrUax7LsJPuOZBplr4IYvZnEGLihl77y2dLdMgG8eR8haSbRmuJrlgfAMBinH4YRuVqp8BFVaLytjBTivIHCDM/hHLW3Ph6hSpU8q51IMyufM0VO4Wf0X8QU9GE1/Fd0B+qtOYVeXneSyr+Z5e/W2w8SJnWuWI2Zw6vIRzlLGpwn32nl4w+4kzmBcW7hIZGLrDJmLQVCCAmTh1TdRpJJfPoL+RToE8d/h42Jy0DWDeiUidcRobCac1zxEnC/lmJU9lr6OBAbyQgLFGIcGNYgi1MCKw2rI9M3s/Ahhjl5RhUE0WAG/1lJLqjTX+lrnr0lT8yoqlu4IKs8GN/gy6PKEikVLuFV+ogO0/rM2YS7NIJH+GbUSMNLrWVQMav2z94MeDzXLseYoa7Gvty9uGPErfsKaQCdQf0AblmFh/U6J3xQX2EofmC+Ux8u0Ze9mn3a0Z+7+hI2UHZsrsHGqZDTG2ATkf+mSJmUYaHTYt0R2CMJtjyAXP2UlJ0F/1Nhi9Y/mFsYtbTrQBpomvys3cjE24T4quprtJbZkDkS2tsNlx+3NvmMbeUBBskHT5XOJy7yO1Us2FQTgM=
  on:
    tags: true
    repo: hmil/express-youch
  skip_cleanup: true
