language: node_js
node_js:
- lts/*
- node
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: hadrien.milano@gmail.com
  api_key:
    secure: Db21Po4A6X/ZzuPZyou9XDsGHrV+O5XEYa9d9RATYxpvc71LBPIM6yUSbjjHkjDgJloV5z93jM06s33vEL06nhlujlxQmhjDKBJL0UeAU/VsbD7qGmHclxyIGP+H4oJxYiPsUbnL9xw2pi5uDTD3xvtl/aG2U7DnlbI5QPAgqtJyoJXWNMN01l3qRQ4OixdnBRh8pzkS4b+7rv2+KFRJCvRrQKmIb/iMZM77uMHzLi2ER/buVLBXmqGCwlcz7SuQx+A/Sk2xvoq1QC9h605WL09OdpfUX4NM6U86985DoBKiT7WErXNLDDW8FL5bayA0gP9/ZDUR8d8wLA5foGEIFS1lmQBnbkT0bUBdX1h2hkUT103pOax+5N6j3exoyzCCTeONrEOIW584OvyJ0S6ef9NRupKVmda66NtlPS07dsDFmHoUuyRQnm8G5FuiqGU5et93w4maJGXYI6h9fcfdwaS8ePgvYg0Iw445assv2g8Rak/Q4UffurGf0xK9Eh2E4VVDZcbtTbGytK9VHfr+vd79dr46Fm/Xx3PZvIenYPzGvejVGJ/+aB8IomeL5RzJtEHffAy2yO1x+ZR10ij7MfFBxkjDv2SgnN5d+lRVuVIvSnzcRdZq2OJVGA+EBIvEBhGejPAZGHMr5NNi0ANPVleGhtypdMJzYCmYHctiaoE=
  on:
    tags: true
    repo: hmil/express-youch
  skip_cleanup: true
